### ISSUE TITLE
Temporal Spec needs Charter

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#1]
If an [OGC Abstract Specification](https://www.ogc.org/docs/as), to be part of the baseline Topics, is to be written, a Standard Working Group needs to be chartered.

The Temporal Domain WG previously produced a draft Best Practice document concerning time, and had the remit to do so, but does not have the remit to produce an Abstract Specification, which has the same status as a Standard.

**Comment by cmheazel** [comment]
Looks like we have a topic for the Huntsville meeting.  I'll put together a draft.

**Comment by chris-little** [comment]
If we can pull most of these issues together in the next few days (three week rule Thursday 18 May) we could decide to ask for OAB approval to release for public comment. I think this a good target.

**Comment by cmheazel** [comment]
The draft charter is at https://github.com/opengeospatial/Temporal-Abstract-Spec/blob/master/Charter/document.html

**Comment by chris-little** [comment]
So Plan B is in place ;-)
