### ISSUE TITLE
What are the attributes & components of a Calendar? 

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#11]
A calendar usually has serveral underpinning timescales with their clocks and ticks and tick names/UoM.

A calendar also needs to relate these timescales to each other usually via algorithms or observations (events) or both.

There are also `Intercalations` - fudges to make everyting fit. These may be seconds, hours, days, possibly weeks, and months that I know.

**Comment by cmheazel** [comment]
Proposition: a calendar is an Ordinal temporal reference system.  I can build a calendar based on phases of the mood, seasons of the year (elevation of the Sun at noon), and solar time of day (sunrise, noon, etc.). Or it could be based on significant events (Saints days, beginning of the Kings reign, etc.). A clock is not required. 

Furthermore, a clock does not require a calendar (UNIX system time).

**Comment by cmheazel** [comment]
Traditionally we have defined calendars based on terrestrial observations of astronomical events. What about calendars for residents of the Moon, or Mars, or star-dates?  Our concept of calendar should accommodate non-terrestrial calendars as well as terrestrial.

**Comment by chris-little** [comment]
> Traditionally we have defined calendars based on terrestrial observations of astronomical events. What about calendars for residents of the Moon, or Mars, or star-dates? Our concept of calendar should accommodate non-terrestrial calendars as well as terrestrial.

Agreed. Calendars are social constructs: 
1. Ancient Egypt used the heliacal (summer) rising of of Sirius to predict the flooding of the Nile and crop planting time. Tied to our solar year

2. Mayan used a calendar based on Venus appearing as morning and evening stars, not tied to the solar year, to predict, as far as I can tell, whether to go to war or not!

3. People working with the Martian Rovers constructed a Martian calendar of a Martian Year and Martian days, called 'sols'. No months. 

I do not think the proposed abstract model precludes these. I suggest we just need these other examples. I can give references.

**Comment by chris-little** [comment]
> Proposition: a calendar is an Ordinal temporal reference system. I can build a calendar based on phases of the mood, seasons of the year (elevation of the Sun at noon), and solar time of day (sunrise, noon, etc.). Or it could be based on significant events (Saints days, beginning of the Kings reign, etc.). A clock is not required.

@cmheazel Having now thought about this again, I think a calendar could be an amalgam of both temporal and ordinal ref systems, but I don't think we should go that way. 

Seconds in the Gregorian calendar are defined by atomic clocks, so a clock timescale is part of some calendars.
As soon as one counts days or months or years and starts notching a wooden stick, that is a clock too, though the ordinal ref system is needed sometimes, such as when to start counting.

If we can capture that dependency on events from Ordinal Reference Systems via attributes, that means the Mermaid diagram stays simple, and consistent with the one in ISO19111 and consistent with the W3C OWL Time ontology.

A key factor is that timescales and clock ticks are "regular" and an ordered sequence of events is irregular and probably not predictable a priori. 

That is why I split things up the way that I have. Are you happy with that?

**Comment by chris-little** [comment]
@cmheazel ~i think we have bottomed out this issue, and the diagram captures enough complexity, so closing the issues. We can always re-open.
