### ISSUE TITLE
Should "temporal geometry" (multi-instants, multi-intervals, etc) be in the Abstract Conceptual Model?

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#13]
Many people have made strong analogies between spatial and temporal structures. Sometimes this has gone too far!

In spatial geometry, there are points, lines, areas, multi-points, etc.

In "temporal geometry", `multi-instants`, `multi-intervals`, `regular multi-instants` and `regular multi-intervals` have been identified as useful things, underpinning time -series of data, etc.

Should these be in the Abstract Conceptual Model? Or perhaps they would sit neatly with the Allen Algebra/Relations?

**Comment by chris-little** [comment]
The one-dimensional Allen Algebra works fine on any single dimension, or separable compositions of them (e.g. Vertical, or Time, or vertical+time, wavelength, etc)
The simple Allen Algebra does not work on the inseparable (x,y) space, which is why the Egenhoffer/Herring 9DIM etc algebras were invented.
If we always split 4D space into ((x,y),z,t) components, we should be OK. At this stage, I see no reason to invent complicated 3D polyhedrons/solids or 4D polytopes/envelopes for combined3/4D geometries. 
Let's get the basic on one dimensional time sorted first.

**Comment by cmheazel** [comment]
We developed 4D coordinate reference systems and transformations in Testbed 18.  In Testbed 19 we are maturing that technology.  I would like to see that knowledge included in this spec.

**Comment by chris-little** [comment]
@cmheazel I've just re-read the Testbed 18 ER. I do not see anything that the proposed abstract conceptual model for time could not support.
Are there any attributes/properties from those UML diagrams and models that should be 'raised up' to these superclasses? Perhaps something around pre-registered definitions versus defined dynamically 'on the fly'?

**Comment by chris-little** [comment]
Agreed at Temporal DWG 2023-08-22 to c lose
