### ISSUE TITLE
How should we manage this repo?

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#14]
At present there are no controls on changes to this repo. I propose that, as the document gets closer to proper draft, that all changes are via merging of Pull Requests, and that they are approved by at least two people.

Initially I suggest the three co-chairs as possible approves (@chris-little , @cmheazel ans @ronTse) and anyone who feels passionate about delivering this document.

**Comment by chris-little** [comment]
Now that we have at least 3 team members with write permission (as well as OGC Staff), I have now enforced merge from approved pull Requests, 2 approvals needed. Hopefully, this will not be too restrictive.

There are lots of other options that we could apply, but we can do that when the need is understood, and we could raise a new issue.

@ronaldtse @cmheazel Are you happy that I close this issue?

**Comment by cmheazel** [comment]
Let's close this issue.

**Comment by ronaldtse** [comment]
Thank you @chris-little and @cmheazel !
