### ISSUE TITLE
Integration with ISO Standards

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/Temporal-Abstract-Spec#15]
Our Abstract Specification has to align with ISO 19111, ISO 19108 and potentially a few other OGC and ISO Standards.  I have added a "Context" section where I have started this analysis.  This section is based on a UML model built on Enterprise Architect. That model is an extension to the TC 211 Harmonized UML model.

One output from this effort will be change requests to the ISO standards.

**Comment by chris-little** [comment]
@cmheazel I do not think we should maintain any alignment with ISO19108 as it has been superseded by ISO19111:2019. I thinkthis document is consistent with ISO19111 and W3C Time in OWL.

**Comment by cmheazel** [comment]
@chris-little From the ISO Web Site for [ISO 19108](https://www.iso.org/standard/26013.html) "This standard was last reviewed and confirmed in 2021. Therefore this version remains current." I don't mind not aligning with 19108, but mainly because I think we can contribute to an update.

**Comment by chris-little** [comment]
@cmheazel I will change the wording from (now obsolete) to (nnow largely superceded)

**Comment by chris-little** [comment]
@cmheazel The Terminology Section is certainly compatible with ISO. Do you agree we should delete any terms that are not referenenced?

**Comment by cmheazel** [comment]
@chris-little  Let's hold on to them for now.

**Comment by chris-little** [comment]
@cmheazel @ronaldtse The problem just got worse. I have just seen an ISO FDIS (Final Draft International Standard), dated 2023 with this vocabulary. For conciseness, I've removed the Notes and Examples, which are extensive.

I do not think this undermines the conceptual model. In particular, I think the `timescale` and `timeline` distinction is clearer than ISO's different kinds of timescale depending on whether they are part of a clock system or a calendar system.
```
date - time (3.2) on the calendar system (6.1) time scale (3.5)

time - mark attributed to an instant (3.4) or a time interval (3.6) on a specified time scale (3.5)

proper time - time (3.2) on a proper time scale (4.1)

coordinate time - time on a coordinate time scale (4.2)

time axis - mathematical representation of the succession in time according to the space time reference of instantaneous events along a unique axis

instant - point on the time axis (3.3)

time scale, timescale - system of ordered marks which can be attributed to instants (3.4) on the time axis (3.3), one instant being chosen as the origin

time interval - part of the time axis (3.3) limited by two instants (3.4)

closed time interval [a,b] - time interval (3.6) that includes both the beginning instant (3.4) and the final instant

open time interval (a,b) - time interval (3.6) that does not include either the beginning instant (3.4) or the final instant

right half-open time interval, contiguous time interval [a,b) - time interval (3.6) that includes the beginning instant (3.4) but not the final instant

left half-open time interval (a,b] - time interval (3.6) that includes the final instant (3.4) but not the beginning instant

recurring time interval - series of consecutive time intervals (3.6) of identical duration (3.7)

duration - non-negative quantity attributed to a time interval (3.6), the value of which is equal to the difference between the quantitative times of the final instant (3.4) and the initial instant of the time interval

negative duration - duration (3.7) in the reverse direction to the proceeding time scale (3.5)

time of day - time (3.2) occurring within a calendar day (7.13)

basis time of day - time of day (3.8) in a basis time scale (4.3)

UTC of day - time of day (3.8) in UTC (4.7)

local time of day - time of day (3.8) in a local time (4.6)

time shift - difference between the marks attributed to the same instant (3.4) between times (3.2) of two time scales (3.5)

equation of time - difference between mean solar time and apparent solar time, which varies with time within a calendar year (7.23)

proper time scale - time scale (3.5) produced by a continuously running primary frequency standard not compensated for gravitational frequency shift

coordinate time scale - time scale (3.5) independent of the equations of motion of material bodies and in the equations of propagation of electromagnetic waves

basis time scale - time scale (3.5) established to serve as reference time by a competent authority

standard time - time scale (3.5) derived from a basis time scale (4.3) with a time shift (3.9) established by a competent authority

adjusted time -  time scale (3.5) derived from a basis time scale (4.3) with a time shift (3.9), established by a competent authority that also defines a standard time (4.4)

local time, local time scale - time scale (3.5) applied locally of either a standard time (4.4) or adjusted time (4.5), as decided by a  competent authority
```

**Comment by ronaldtse** [comment]
@chris-little sorry I've been out of the loop recently due to some familial matters...

ISO/FDIS 34000 has just been approved and will be published soon. TC 154/WG 5 can always discuss your latest proposals on "timescale" and "timeline" in an updated 34000 in the future.

**Comment by chris-little** [comment]
@ronaldtse @cmheazel Another source of terminology is Chapter 6 of the [MISB MISP-2023.2: Motion Imagery Handbook
March 2023](https://nsgreg.nga.mil/doc/view?i=5470).

MISB: Motion Imagery Standards Board

MISP: Motion Imagery Standards Profile

It has some good diagrams and detailed syntaxes for handing nanosecond precision timing, synchronization, and coordination.

It is probably not suited to an abstract conceptual model, but would be good material for a logical or implementation model or Best Practice -which is what it is!

**Comment by chris-little** [comment]
An Enterprise Architect UML model of the Abstract Conceptual Model for Time as now been added to the repo.

**Comment by chris-little** [comment]
Agreed at Temporal DWG 2024-05-08 to close as largely met by OGC 23-049.
