### ISSUE TITLE
Does a Calendar class have one (complex) algorithm or many (simpler) algorithms?

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#25]
E.g. for the Gregorian Calendar, should 'number of days in a month', 'number of hours in a day', and 'which years are leap years' be consider separate algorthims or part of a single whole?
I prefer the simplest approach of a (complicated) algorithm per calendar.
Other views requested.

**Comment by cmheazel** [comment]
A 1-to-n cardinality may work best.  The algorithms specified for a calendar should be recognizable to the users of that calendar.  One to N allows us to use a single complex or multiple simple algorithms as appropriate.

**Comment by chris-little** [comment]
Agreed, and diagram reflects this.
