### ISSUE TITLE
Which terms and definitions in Clause 4 can be deleted

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#28]
The terms and Definitions section, Clause 4, defnes most terms used in a range of other standards. Only those relevant to defining and understanding the conceptual model should be retained.

**Comment by chris-little** [comment]
The groups of definitions that could be removed, or added as examples to the conceptual model, seem to include these CRSs and datums:
* Compound CRS
* Derived CRS
* Dynamic CRS
* Engineering CRS
* Linear CRS
* Parametric CRS
* Spatio-parametric CRS
* Spatio-parametric-temporal CRS
* Spatio-temporal CRS

And also these Reference Frames and datums/epochs:
* Dynamic RF
* Parametric Reference Epoch
* Static RF
* Terrestrial RF

**Comment by cmheazel** [comment]
I think so.

**Comment by chris-little** [comment]
@cmheazel Let's copy "Coordinate" definition across first from the Glossary

**Comment by chris-little** [comment]
@cmheazel `Coordinate` definition copied across and also removed from Glossary with PR#34
