### ISSUE TITLE
Bibliography needs trimming

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#29]
Like the Terms and Definitions, the Clause 4 section, the Biblography, is a portmanteau of lots of references. Only those needed for the definition or understanding of the conceptual model are needed.
"When in doubt, cut it out!"

**Comment by chris-little** [comment]
@cmheazel Please check out references and bibiliography.

**Comment by chris-little** [comment]
@cmheazel I'm having difficulty in getting emaikls out across the Atlantic for some reason, so seeing if this works.

**Comment by cmheazel** [comment]
Concur. I'll close the issue.
