### ISSUE TITLE
Top level UML Class diagram needs links and cardinalities correcting

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#4]
Currently, the classes (taken from ISO19111:2019) are linked by Composition. Should the link type be something else? and what should the cardinalities be?

**Comment by cmheazel** [comment]
The classes from ISO 19111 should not be modified. We can extend what is already standardized, but we cannot change it.

**Comment by chris-little** [comment]
I have now added several attributes/properties to the diagram, but more work to be done, and diagram simplified by agreeing on representation of inheritance.

**Comment by chris-little** [comment]
Sam Meek identified  problem with 'diamond inheritance' in the diagram, so I have removed implicatons of inheritance between the classes/objects by using aggregation.
The diagram is now fully annotated with multiplicites, properties, etc so I will close this issue
