### ISSUE TITLE
Public Comment 1.4 The Abstract needs improving

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#49]
@cnreediii suggested that the first couple of lines of the Abstract could be improved with a statement of what problem is the focus of this Abstract Spec.

**Comment by chris-little** [comment]
@cnreediii I propose to switch the first two paragraphs around to address your concern.

**Comment by cnreediii** [comment]
@chris-little SOunds good.

**Comment by chris-little** [comment]
@cnreediii @samadammeek Is the abstract good enough for me to close this issue please?

**Comment by cnreediii** [comment]
@chris-little I will send you a short Word file with mt suggested edits. The main suggestion is that rather than just state [ISO19111], the full title should be provided in the first usage or reference to a specific standard. Thanks

**Comment by chris-little** [comment]
@cnreediii Incorporated your suggestions in PR #87

**Comment by cnreediii** [comment]
@chris-little Thanks!

**Comment by chris-little** [comment]
PR #87 merged and issue closed.
