### ISSUE TITLE
How many attributes should be add to top level class diagram?

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#5]
The class diagram in ISO19111:2019 does not show any attributes or methods. Should there be any, and what?

**Comment by chris-little** [comment]
I have added some text to the spec to outline my thinking and what potential attributes should be.

I thinkn we need also to have objects: clock, timescale, units, count, event, starttime (epoch), endtime.

A timescale could be conposed of several other timescales or clocks.

**Comment by cmheazel** [comment]
I have been working with the ISO TC211 Harmonized UML model.  This provides us with a normative UML model to work with, not just a few diagrams.  We can generate any diagrams we need from this model.  At the same time, we should not be modifying classes which are already standardized.  

A diagram is not a model. It is simply one view into the model.

**Comment by chris-little** [comment]
I have some issues with the ISO Unified approach:
1. there is widespread consensus that the derived ontologies are not realistic and are unusable.
2. ISO19108 Temporal Schema is not abstract - it is an implementation schema, and does not seem to recognise non-Gregorian calendars
3. ISO19108 was not updated, and is largely replaced by ISO19111.
4. I think this proposal could replace ISO19108 as an abstract conceptual model in the ISO Harmonised Model.

But keep it simple, otherwise users will not understand it or use it.

**Comment by chris-little** [comment]
@cmheazel Can we close this?

**Comment by chris-little** [comment]
Agreed at Temporal DWG 2023-08-22 with @cmheazel
