### ISSUE TITLE
Does the top level `Reference System` need any attributes or properties?

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#6]
As the top level `Reference System` is a super-class and probably does not need any other attributes or properties? I cannto think of any. Do you all agree?

**Comment by chris-little** [comment]
Dimension of the reference system  may be useful. 

`Reference System` could have a dimension of 1 or greater. 

`Temporal Reference System` should have a dimension of `1`.

Thoughts?

**Comment by chris-little** [comment]
I have changed the Mermaid diagram to treat Domain of Applicability to be an attribute.

**Comment by cmheazel** [comment]
ISO 19107 Edition 2 provides a ReferenceSystem interface class. However I have not found any association between the 19107 class and any 19108 or 19111 classes.  Ideally the ReferenceSystem class would be a root class for all three of these Standards.

**Comment by chris-little** [comment]
Do Interfaces need to have a place in this abstract conceptual set of classes? Surely they are for logical or implementation models?

**Comment by chris-little** [comment]
@cmheazel Can we now close this too?

**Comment by chris-little** [comment]
Agreed at Temporal DWG 2023-08-22 wit h @cmheazel
