### ISSUE TITLE
Remove surplus glossary

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#69]
The glossary was maintained from earlier work to ensure no topics were missed, based on an ISO glossary. All the terms for the Abstract Conceptual Model for Time are in the `Terms and Definitions` and other referenced standards.

@cmheazel I propose to remove the complete section. We could copy it to elsewhere in the repo, and and combine with the recent DIS34000 temporal glossary for future work.

**Comment by cmheazel** [comment]
I concur.  Go ahead and remove the glossary.

**Comment by chris-little** [comment]
PR #87 will be generated.

**Comment by chris-little** [comment]
PR #88 awaiting merge.

**Comment by chris-little** [comment]
@cmheazel I am also removing the surplus outdated PlantUML PNGs and copied the glossary to the UsefulStuff folder.
