### ISSUE TITLE
What are the attributes of Events and Ordinal Temporal Reference Systems?

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#7]
Here is my first proposal for the attributes and properties of Events and Ordinal Temporal Reference Systems:

- `Name/Id` maybe a human readable name and a machinable reference to a register? **Mandatory**
- Class of Events ?
- Listed or enumerated sequence of events **Mandatory**
- First and last events **Mandatory**  perhaps Optional if hard to define abstractly?
- Epoch, defined in some other temporal reference system **Optional**
- Location or region of applicability **Optional**

**Comment by chris-little** [comment]
I have incorporated these attributes into the text and Mermaid diagram.

**Comment by chris-little** [comment]
And how should we show that the 2 or more events of an ordinal temporal reference system are fully ordered?

**Comment by cmheazel** [comment]
UML allows you to specify that a set of attributes are ordered.

**Comment by chris-little** [comment]
Now done on diagram
