### ISSUE TITLE
Do we need Conformance Tests?

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#70]
@cmheazel @ronaldtse At present the spec has no Conformance Tests. Do we need any? If we do, what form should they take? Would they be only by inspection of a temporal artefact?

**Comment by chris-little** [comment]
Abstract Spec Topics do not need to have Abstract Test Suites or Conformance Classes unless they make sense. Per TC Policy…

"The detail of the Abstract Specification shall be sufficient to provide normative references, including models, and technical guidelines as a foundation for Standards. Each Topic, to the extent possible, provides unambiguous normative and informative information that allows for implementation of Standards in software.

The level of detail of the Abstract Specification is at the discretion of the TC as reflected by the actual content that is approved for inclusion in the document itself.”

I conclude we do not need them.

@cmheazel @ronaldtse Do you agree?

**Comment by cmheazel** [comment]
I concur.

**Comment by chris-little** [comment]
Addressed by PR #86 .
