### ISSUE TITLE
Public Comment 1.8.1 Detailed editorial suggestions

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#73]
1. General: Regarding cross-references to the bibliography: there is no textual indication that a cross-reference to an item in the bibliography is present. Thus it is not possible to see that there is a link when the document is printed. Consider adding [x] to the citations. [REJECTED]
2. Section 6: Regarding: "A conceptual model starts with a glossary of terms and definitions". This does not seem correct. When describing a conceptual model in a document, the document can start with a glossary of terms and definitions, but the conceptual model itself does not start with a glossary of terms and definitions. Suggest rephrasing to something like: "A conceptual model contains the terms and definitions of the concepts it organizes." or, alternatively "A conceptual model contains the definitions of the concepts it organizes." as bullet 3 already seems to mention the terms (vocabulary). [DONE]
3. Section 7: Please make the UML model in Enterprise Architect and add definition etc. of the model elements to the model itself as well. [PENDING]
4. Section 8.2: Make sure that the figure caption contains the phrase "Allen operators" and a reference to Maintaining Knowledge about Temporal Intervals [DONE]
5. Sections 7 and 9: Rename section 9 from "Attributes of the classes" to something that also covers that the classes themselves are described, not only their properties. [DONE]
6. Consider placing Figure 1 in section 9 (and thus removing section 7) as these (should) go together. [DONE]
7. Section 9: Be consistent in the way the names of the elements are written. Right now, it is a mix of camelcase, terms with spaces using upper case and terms with spaces using lower case. I would suggest to use plain English, in lower case, in the text, and keep the camel case for the diagram. So e.g. "An ordinal temporal reference system is a type of temporal reference system. Therefore, the ordinal temporal reference system class inherits the following attributes from the temporal reference system class" instead of "An Ordinal Temporal Reference System is a type of temporal reference system. Therefore, it inherits the following attributes from the TemporalReferenceSystem class". [DONE]
8. Bibliography: The issue number and the persistent URL are missing for Allens publication. Change to: Allen, J. F. _Maintaining Knowledge about Temporal Intervals_ Communications of the ACM, 1983, vol. 26, no. 11, pp. 832-843. [https://doi.org/10.1145/182.358434](https://dl.acm.org/doi/10.1145/182.358434) [DONE]

**Comment by chris-little** [comment]
@heidivanparys I will start on a PR for these editorial suggestions.

**Comment by chris-little** [comment]
> Consider placing Figure 1 in section 9 (and thus removing section 7) as these (should) go together.
Good suggestion. After Regimes and before details.

**Comment by chris-little** [comment]
> Section 6: Regarding: "A conceptual model starts with a glossary of terms and definitions". ... Suggest rephrasing to something like: "A conceptual model contains the terms and definitions of the concepts it organizes." or, alternatively "A conceptual model contains the definitions of the concepts it organizes." as bullet 3 already seems to mention the terms (vocabulary).

Replaced with "A conceptual model contains the definitions of the concepts that it organizes."

**Comment by chris-little** [comment]
> Section 9: Be consistent in the way the names of the elements are written. Right now, it is a mix of camelcase, terms with spaces using upper case and terms with spaces using lower case. I would suggest to use plain English, in lower case, in the text, and keep the camel case for the diagram.

plain English adopted. Thank you. A good suggestion.

**Comment by chris-little** [comment]
Section` 7: Please make the UML model in Enterprise Architect and add definition etc. of the model elements to the model itself as well.

@heidivanparys The diagram was constrained by:
1. My ignorance of UML - so I am an ideal reader. The document is not aimed at UML experts;
2. The use of Mermaid which displays directly inside GitHub. See https://github.com/opengeospatial/Temporal-Abstract-Spec/blob/chris-little-PC1.8/abstract-specification/sections/06-other-clauses.adoc
3. @cmheazel has access to EA so will try to construct the model strictly.

**Comment by chris-little** [comment]
> General: Regarding cross-references to the bibliography: there is no textual indication that a cross-reference to an item in the bibliography is present. Thus it is not possible to see that there is a link when the document is printed. Consider adding [x] to the citations.

When the final document is generated, as pdf, Word or HTML, the cross references should all appear as underlined hyper links, so that the [1] notation is not needed. IF this does not happen, we can re-edit, but for now, I do not propose to change anything.

**Comment by cmheazel** [comment]
Action Chuck - make sure the EA model aligns with the Abstract Spec then package for delivery with the Standard.
