### ISSUE TITLE
Public Comment 1.8.2 Minor, non-editorial

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#74]
1. Sections: Preface, 3, 9.4.3, 10: The specification refers to ISO 8601:2004. However ISO 8601 was revised a couple of year ago. Is it necessary to refer to a particular edition of ISO 8601, or would an undated reference to ISO 8601 suffice? [DONE]
2. Section 7: In Figure 1, property SpatialReferenceSystem::dimension can be removed, it is already inherited from ReferenceSystem and is not redefined by SpatialReferenceSystem. [DONE]
3. Section 7: In Figure 1, properties OrdinalTemporalReferenceSystem::dimension, TemporalCoordinateReferenceSystem::dimension and Calendar::dimension can be removed, that property is inherited from TemporalReferenceSystem and it is not redefined in the specializations. [DONE]
4. Section 7: In Figure 1, properties TemporalReferenceSystem::applicationLocationTimeOrDomain, SpatialReferenceSystem::applicationLocationTimeOrDomain, OrdinalTemporalReferenceSystem::applicationLocationTimeOrDomain, TemporalCoordinateReferenceSystem::applicationLocationTimeOrDomain and Calendar::applicationLocationTimeOrDomain can be removed, that property is inherited from ReferenceSystem and it is not redefined in its specializations. [DONE] Also, property applicationLocationTimeOrDomain seems an odd construct in a conceptual model (in a data model / application schema one can encounter this, for practical reasons). Take ReferenceSystem:applicableLocationTimeOrDomain, split it into three and use the terminology used in 9.1: (1) "locationOfApplicability", "timeOfApplicability", "domainOfApplicability". [DONE]  Adjust the multiplicity if needed (is it 1? is it 0..1? can those properties be multivalued?). [DONE]
5. Section 9.2.1: The text reads "The Events class is an ordered list of temporal events." So, an event is a list of events. This is not true. What is described is the (unnamed) property of OrdinalTemporalReferenceSystem that has "Event" as type, not the class Event itself. Defined Event ("a thing that happens"?). [DONE]
6. Section 10: Why is only RFC 3339 listed here? Why are ISO 8601-1 and ISO 8601-2 not listed here? I know those are not available for free, but they should as minimum be listed here (and in the bibliography). Consider adding [https://datatracker.ietf.org/doc/draft-ietf-sedate-datetime-extended/](https://datatracker.ietf.org/doc/draft-ietf-sedate-datetime-extended/) and [https://www.loc.gov/standards/datetime/edtf.html](https://www.loc.gov/standards/datetime/edtf.htm) here (and in the bibliography) as well. [DONE]

**Comment by chris-little** [comment]
> Section 10: Why is only RFC 3339 listed here? Why are ISO 8601-1 and ISO 8601-2 not listed here? I know those are not available for free, but they should as minimum be listed here (and in the bibliography). Consider adding https://datatracker.ietf.org/doc/draft-ietf-sedate-datetime-extended/ and [https://www.loc.gov/standards/datetime/edtf.html](https://www.loc.gov/standards/datetime/edtf.htm) here (and in the bibliography) as well.

The generic ISO8601 is now listed, but a restrictive profile is much simpler, unless the later version of ISO8601:2019 removes lots of flexibility. The notation in ISO 8601-2 is not referenced. This is not a standard about instances of temporal constructs, just the fundamental concepts.

**Comment by chris-little** [comment]
> Take ReferenceSystem:applicableLocationTimeOrDomain, split it into three and use the terminology used in 9.1: (1) "locationOfApplicability", "timeOfApplicability", "domainOfApplicability". [DONE] Adjust the multiplicity if needed (is it 1? is it 0..1? can those properties be multivalued?). 

Initially, Kept It Simple, chose multplicity of 0..1 e.g. location: Earth/Mars/Middle Earth or time: Holocene/Pangaea or domain WGS84 Ellipsoid/Jungfrau train tunnel/my home office AR/MRI Scan/mesosphere.  Obviously there is some possible overlaps, which is why I lumped them together originally.

**Comment by ronaldtse** [comment]
From the perspective of ISO/TC 154/WG 5 it is certainly preferred to either cite ISO 8601-1:2019 and ISO 8601-2:2019 individually or incorporate an “all parts” citation to “ISO 8601 (all parts)”. 

The LOC’s EDTF standard is incorporated into ISO 8701-2:2019 if you wish to cite an ISO standard instead.

**Comment by chris-little** [comment]
@ronaldtse PR#83 changed citation to the generic ISO8601.

And addressed the other issues abouve.
