### ISSUE TITLE
Public Comment 1.8.3.1 No SHALLs implies no normative references

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#76]
Section 3: There is not a single requirement ("shall" statement) in the document, and consequently also no requirements requiring that the standardization target of this document (there is none?) has to conform to a certain specification (such as ISO 19111). Therefore, no normative references should be present. Either move the normative references to the bibliography or add/rephrase those parts that justify the presence of normative references (are those parts "This Temporal Abstract Conceptual Model follows ISO 19111:2019, which is the ISO adoption of OGC 18-005r4. The model is also informed by the W3C Time Ontology in OWL.")). I know that the difference between normative and informative references is not really described in the modular specification, but on this point, it would really be good to follow the ISO practice regarding normative references ([https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor193](https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor193)). [REJECTED]

**Comment by chris-little** [comment]
Abstract Spec Topics do not need to have Abstract Test Suites or Conformance Classes unless they make sense. According to OGC Technical Committee (TC) Policy…

"The detail of the Abstract Specification shall be sufficient to provide normative references, including models, and technical guidelines as a foundation for Standards. Each Topic, to the extent possible, provides unambiguous normative and informative information that allows for implementation of Standards in software.

The level of detail of the Abstract Specification is at the discretion of the TC as reflected by the actual content that is approved for inclusion in the document itself.”

The most recent Topics: GeoPackage has no Abstract Test Suite, but Tiling and DGGS do. Most of the earlier ones do not.

We propose to add some text to state that there is no Abstract Test Suite or conformance classes, as it is an Abstract Conceptual Model and any tests would have to be inspection of an existing implementation or design to identify the presence of the model components.

**Comment by cmheazel** [comment]
Re the issue about normative references -- the asciidoc does not identify this section as normative.  The "Normative" text is added by Metanorma. We should find a way around this, keeping this section non-normative.

**Comment by chris-little** [comment]
Addressed by PR#86
