### ISSUE TITLE
automated Metanorma builds failing

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#89]
Currently, the recent PR merges have failed to find an image (https://github.com/opengeospatial/Temporal-Abstract-Spec/blob/master/23-049/sections/images/IntervalRelations(CTL).jpg) even though it is found while reading the appropriate section (https://github.com/opengeospatial/Temporal-Abstract-Spec/blob/master/23-049/sections/08-temporal-regimes.adoc)

@cmheazel @ronaldtse @ghobona What needs altering please? The image folder is currently in the Section folder of 023-049. When it was elsewhere in the document tree, I couldn't get it work.

**Comment by cmheazel** [comment]
Chris,

I made a few mods and it built successfully on my machine.  Currently working on GitHub issues which are preventing me from posting back to the repository.

Chuck

From: Chris Little ***@***.***>
Sent: Tuesday, February 13, 2024 3:08 PM
To: opengeospatial/Temporal-Abstract-Spec ***@***.***>
Cc: Charles Heazel ***@***.***>; Mention ***@***.***>
Subject: [opengeospatial/Temporal-Abstract-Spec] automated Metanorma builds failing (Issue #89)


Currently, the recent PR merges have failed to find an image (https://github.com/opengeospatial/Temporal-Abstract-Spec/blob/master/23-049/sections/images/IntervalRelations(CTL).jpg<https://url.emailprotection.link/?b5gDMHbsCupqN81MoZ9rMo7Rz2QxrvDtcxKkzeAkfGzavqn3YsEkiUIVZsqsWDfQOq4BLSAh2EV3iISx-Zmp2vBetNDrWZLiKYZryyi9sdzi-Q1i4IRyOhyRvgV48lBUs0ZdNYqG_ZhDNVJrPab8LT4jd5f9Yitmefl9PLEJzPel3eqHK7nzN-Tm9_oo_R8IeMpBkyGhJKfZWnEJ-lI1Trw~~>) even though it is found while reading the appropriate section (https://github.com/opengeospatial/Temporal-Abstract-Spec/blob/master/23-049/sections/08-temporal-regimes.adoc<https://url.emailprotection.link/?bM6eC5IpYNCKiHj6MiQmBPtw5n-MqEnUW0TpnnvCpe7Q22z8zOHab6_6NvZ9qNp4fYCbkGm33YW19AMS5H_MqwlDHlZjs4rpVmQAzOx1S-VTWZl-aRwjCIX0kPGzFw9CtM88QFccL_7YbZJHKh4sRyT4_7O71ih3pb47_iL6osfg~>)

@cmheazel<https://url.emailprotection.link/?buEq4eyNl9NRYRhKUfm4VcIfJXzK_by8AF03pkmF9N3G-LSw-erH7PqSWitkthvILT-AK-CVYWhFLcWcH7jNXKA~~> @ronaldtse<https://url.emailprotection.link/?buEq4eyNl9NRYRhKUfm4VcK6niip3VflEif62ojFuBjSDVgqJJxhFZS3nOiVEnLjgzomgd-Pxhwqj4tFkZQ0M9A~~> @ ghobona<https://url.emailprotection.link/?buEq4eyNl9NRYRhKUfm4VcAw91Y5BdasRTl_lh0BaPhwfir74EGqzzFwyxf0R8jmai6KUtRI_eIo461hnTa761g~~> What needs altering please? The image folder is currently in the Section folder of 023-049. When it was elsewhere in the document tree, I couldn't get it work.

**Comment by chris-little** [comment]
@cmheazel Thanks. The structure of 23-049 on the repo is straightforward now.

**Comment by cmheazel** [comment]
Chris,

My branch built successfully on the Repo.  You can merge PR 90 now.

Chuck

**Comment by chris-little** [comment]
@cmheazel The PlantUML has not yet got the updated algorithm/timeline change. and why do we need so many copies in the folder?

**Comment by cmheazel** [comment]
I didn’t put them there. I think they are an artifact of PlantUML processing.

Chuck

**Comment by chris-little** [comment]
@cmheazel Ive pushed through a correction to the PlantUML. Let's discuss tmorrow whether to put the extra images or not. They will need some explanatory text.

**Comment by chris-little** [comment]
@cmheazel The IntervalRelations.jpg does not display in my Github, and the link gives a 404.

**Comment by cmheazel** [comment]
It shows up in the downloaded .html and in the .pdf.  I have run into this before, where the GitHub display does not use the same image path as the rendered document.  But as long as the rendered documents are correct, I think it’s something we have to live with.

Chuck

**Comment by chris-little** [comment]
Agreed at Temporal DWG 2024-05-08 to close
