### ISSUE TITLE
What are the attributes & components of a Temporal Coordinate Reference System?

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Temporal-Abstract-Spec#9]
My first proposal for attributes or properties or components of a Temporal CRS:

- Mandatory Name/Id 
- Mandatory name for each tick
- Mandatory whether count increments or decrements for each tick
- Optional Epoch/starting time, defined in some other temporal reference system 
- Optional Start time, defined in  the same temporal reference system as the Epoch 
- Optional End time, defined in the same temporal reference system as the Epoch
- Optional location or region of validity

**Comment by chris-little** [comment]
Propose that a Temporal CRS has a component of a Timescale.
Timescale:
    Mandatory Name/Id
    Mandatory Clock
    Mandatory whether count increments or decrements for each clock  tick
    Optional Epoch, defined in some other temporal reference system
    Optional Start time or count
    Optional End time or count
    Optional Location or region of validity

A Timescale has a component of a Clock (or another Timescale?)
-     **Mandatory** Name/Id
-     **Mandatory** name for each tick duration
-     **Mandatory** count increments for each tick
-     Optional Current Count
-     Optional Start  Count
-     Optional End Count
-     Optional Start time, defined in some other temporal reference system
-     Optional End time, defined in the same temporal reference system as the Start Time
-     Optional Location or region of validity

**Comment by cmheazel** [comment]
How is a temporal coordinate reference system different from any other coordinate reference system?

**Comment by chris-little** [comment]
@cmheazel 

> How is a temporal coordinate reference system different from any other coordinate reference system?

Not much. provided we lump calendars and ordinals with postal/zip codes and addresses, and perhaps linear referencing systems.

But time does seem to have a preferred direction.

**Comment by chris-little** [comment]
A top level attribute has to be an authoritative defining/owning body. I am assuming then the top level attributes are inherited by the sub-classes, but not sure how to do this correctly in UML.

**Comment by cmheazel** [comment]
Attributes are inherited by the sub-classes. Usually they are not shown in the diagrams, but you can make them visible if you want to.

Remember - the diagrams are just views into the model.  There is far more in the model than you can ever see in any one diagram.

**Comment by chris-little** [comment]
> @cmheazel I will add authoritative body as a top level attribute to be inherited. Applies to spatial reference systems too.

Done, but diagram probably could be simplified.

**Comment by chris-little** [comment]
@cmheazel I'm conscious of not turning this conceptual model into a logival model, but I think we need a couple of attributes for Timescale:
1. Bounds: which could be expressed as earliest and latest counts of the clock, or the timescale is unbounded
2. Whether the timescale is discrete (i.e. counts of ticks, supporting integer arithmetic) or continuous (supporting real arithmetic)
Both of those attributes indicate that Timescale is not a component of an Ordinal Temporal Reference System.

**Comment by chris-little** [comment]
@cmheazel We have addressed all these points in this issue, and captured them in the diagram and now the text, so closing this issue. We can always re-open.
